# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('voter_id', models.IntegerField()),
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_id', models.IntegerField()),
                ('election_id', models.IntegerField()),
                ('post', models.CharField(max_length=50)),
                ('college_id', models.CharField(max_length=9)),
                ('college', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('symbol', models.TextField()),
                ('is_verified', models.IntegerField()),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.TextField()),
            ],
            options={
                'db_table': 'election',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('registration_no', models.IntegerField()),
                ('symbol', models.TextField()),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('citizenship_no', models.IntegerField()),
                ('college', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('photo', models.IntegerField()),
                ('dob', models.DateField()),
                ('citizenship_scan', models.TextField()),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('disability', models.CharField(max_length=50)),
                ('college_id', models.CharField(max_length=9)),
                ('college', models.IntegerField()),
                ('citizenship_no', models.CharField(max_length=20)),
                ('photo', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='WinnerReport',
            fields=[
                ('post', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('election_id', models.IntegerField()),
            ],
            options={
                'db_table': 'winner_report',
            },
        ),
    ]
