# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_student_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='default.JPG', upload_to='student-photo/'),
        ),
    ]
