# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20170720_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.FileField(upload_to='candidate_symbol'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='voter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Student'),
        ),
    ]
